AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  GitTemplateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GitTemplateLambda
      Handler: dist/index.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: POST
