name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build with esbuild
        run: npm run build

      - name: Zip Function
        run: zip -j function.zip dist/index.js

      - name: Check zip contents
        run: |
          ls -lh
          unzip -l function.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_ARN }} \
            --zip-file fileb://function.zip

      - name: Publish New Version
        id: publish
        run: |
          VERSION=$(aws lambda publish-version \
            --function-name ${{ secrets.LAMBDA_ARN }} \
            --output text --query Version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Output Version
        run: |
          echo "✅ Deployed version: $VERSION"
        env:
          VERSION: ${{ steps.publish.outputs.VERSION }}
